### ISSUE TITLE
Remove pixels that were not assigned to cells

### ISSUE THREAD

**Issue by janinemelsen** [angelolab/ark-analysis#1108]
Hi!
Since I use a slide scanner for imaging the whole tissue slide, there are always pixels that do not belong to any cells (~15%). They are not zero, since there is always some background staining on these empty spots. Is there a reason why these pixels are still included in the pixel clustering? They kind of mask the true biological signal, since the value of these non-cell pixels can be pretty high for some markers. Is there an easy way in which I can remove those pixels from further downstream processing?

Thanks!

**Comment by cliu72** [comment]
Hi @janinemelsen! Pixie includes pixels not belonging to any cells, by design, because one of the major advantages of Pixie is that it is able to capture extracellular objects (e.g. extracellular matrix, vessels, extracellular aggregates, etc), in addition to cells. Pixie is intended for images that have been pre-processed to remove as many imaging artifacts as possible (since imaging artifacts are often technology-specific). I would recommend trying cleaning up your images as much as possible before feeding into Pixie (perhaps a tissue mask to mask out empty spots would be helpful here).

**Comment by janinemelsen** [comment]
Makes sense, thanks for the quick reply again! Really appreciate:)
