### ISSUE TITLE
Windows Problem With bash start_docker.sh Command

### ISSUE THREAD

**Issue by Nicholas-Bartelo** [angelolab/ark-analysis#1145]
Hello!

I am attempting to install this package today to use Pixie on a Windows machine. I have made it through the installation tutorial up to the step "Setting up the repo". 

Everything seems to be working well until I execute the line `bash start_docker.sh` in the command prompt terminal. The outcome is the error message in the image below. I ran `wsl sudo apt-get install dos2unix` and then retried, but this did not work for me. 

Please let me know if there is a solution to this problem. I look forward to your response and thank you in advance!

![image](https://github.com/angelolab/ark-analysis/assets/77738340/c34104d7-9ff6-47db-ae1d-9e62da76ccaa)

**Comment by cliu72** [comment]
Hi @Nicholas-Bartelo! Sorry about this issue, like you suspect, it's probably a Windows line-ending error. In the lab, we have actually moved away from using docker because it's been causing a lot of issues. Instead, I would suggest running Pixie outside of docker.

To run Pixie outside of docker, create a conda environment with python version 3.11 (actually, 3.9, 3.10, or 3.11 should be okay): `conda create -n ark_env python=3.11`. Then install ark-analysis using `pip install ark-analysis`. Seems like you have already cloned the repo, but if not, clone using `git clone https://github.com/angelolab/ark-analysis.git`. Then navigate into the ark-analysis folder (`cd ark-analysis`) and start jupyter using `jupyter lab`. You should be able to then open the notebook `2_Pixie_Cluster_Pixels.ipynb` (this notebook lives in the `templates` folder in ark-analysis, but I suggest making a copy and moving it somewhere else to avoid confusion - the templates folder will overwrite every time you pull from Github).

All the necessary dependencies should be installed after doing `pip install`. I use a Windows machine and can use Pixie no problem using this method. Please let me know if this works for you.

**Comment by smith6jt-cop** [comment]
The bash script specifies the version number in the docker tag which doesn't match up with "ark-analysis:latest."

Unable to find image 'angelolab/ark-analysis:v0.7.1' locally
docker: Error response from daemon: manifest for angelolab/ark-analysis:v0.7.1 not found: manifest unknown: manifest unknown.
See 'docker run --help'.

May I suggest that if you are having problems with the Docker usage, you take down the instructions to make use of it until the problems are addressed?
