### ISSUE TITLE
look into self-writing documentation

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#140]
There are a couple different options out there to create documentation directly from function docstrings. We should investigate which of these (readthedocs, sphinx, etc) seems the most lightweight and easy for us to adapt

**Comment by saeedseyyedi** [comment]
I think Sphinx is a good one to start with as it is the most comprehensive and most recommended one. Also it has more online resources and documentation to use.

**Comment by alex-l-kong** [comment]
I second Saeed's comments. A lot of Python-based projects use it so it will be easy to find examples online.

**Comment by ackagel** [comment]
yeah sphinx looks the best/easiest to implement.  We might need to rewrite some of the doc-strings into reStructuredText (and/or possibly markdown?).  It also looks like there's an option to theme Sphinx's html output to look like the prettier read-the-docs output, with just the addition of the `sphinx-rtd-theme` package.

**Comment by alex-l-kong** [comment]
As for reST vs Markdown, Sphinx by default supports reST. There are ways to use Markdown but it requires more configuration.

On the other hand, the biggest complaint against reST is that it suffers from a higher learning curve and can be a bit unwieldy at times. For the purposes of our project (completely Python-based, for example, so no need for multiple-language documentation support), it probably offers more than what we need.

It seems that at one point reST was the best because Sphinx didn't come with a built-in Markdown parser, meaning you had to write your own. However, according to Sphinx's documentation, they are now fully integrated with a parser called recommenmark: https://www.sphinx-doc.org/en/master/usage/markdown.html.

It might be a bit more work to set up Markdown for Sphinx, but in the long run, I think it will be easier to work with.

**Comment by ngreenwald** [comment]
What about if we have R code in the repo? I know R is also markdown
friendly, but will it work from two different languages? Or is that one of
the advantages of reST?

**Comment by alex-l-kong** [comment]
Sphinx/reST's advantage is that it does support multiple languages by default. I'm not 100% certain if it's possible to configure Markdown with Sphinx to support polyglot documentation (Python/R in our case), but I would imagine that at the very least it would involve more work. @saeedseyyedi any comment?

**Comment by ackagel** [comment]
Python+R should be fine.  idk if it'll do it under one single run, but as long as the lang's are separated (folder-wise), we can just run it once for each lang so that we just get their respective html pages, and work-with/combine those.

**Comment by ngreenwald** [comment]
Got it. Will from Van Valen lab also recommends Markdown over reST

**Comment by saeedseyyedi** [comment]
Both python and R would work!
@ngreenwald do you know why Van Valen folks recommend Markdown over RST?

**Comment by ngreenwald** [comment]
The syntax is apparently more annoying and tricky to work with, whereas
markdown is fairly lightweight and intuitive to work with
