### ISSUE TITLE
compute_closenum speed up

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#161]
Currently, when you push to GitHub, there's a slight bottleneck in the test_calculate_channel_spatial_enrichment and test_calculate_cluster_spatial_enrichment due to calls to compute_close_cell_num and especially compute_close_cell_num_random. We should look into making these functions more efficient so we can speed up the testing process. It would also allow for higher bootstrap_nums to be used for higher-confidence results.

**Comment by ackagel** [comment]
I wrote a super (x10-x100) speed up for the bootstrapping (`compute_close_cell_num_random`) but I have some questions about the function @ngreenwald @Jaiveers21.

There are two lists of num cells per marker passed in.  The first, looks to be exactly number of cells per each marker.  i.e `mark1_num[0]=num_cells_of_type_0`.  However, the second, appears to be the same but redundantly computed once per iteration of the first. i.e `mark2_num.size == mark1_num.size^2` w/ `mark2_num[k+n*mark1_num.size] == mark1_num[k]` (`k, n < mark1_num.size`)

Is this assessment correct?  If so, is there any reason for this that I'm missing?

**Comment by ngreenwald** [comment]
Where are you seeing that the second is redundantly computed?

**Comment by ngreenwald** [comment]
Wait a minute, let me think about this

**Comment by ackagel** [comment]
I see the redundancy most directly in `compute_close_cell_num`.  Plus, it looks like the size used in the test function is 20 and 400 respectively (the test function only tests for the correct shape, which probably needs to change at some point).

**Comment by ngreenwald** [comment]
Yes, I agree. The reason the code was written this way was because it's an extension of the compute_close_cell_num function. 

We want to get all pairwise interactions between the markers in the list. So have a nested for loop, the first looping over one marker, the second looping over a second marker. In that for loop, we're duplicate work, which is calling get_pos_cell_labels n*2 times instead of n times. We can pre-compute get_pos_cell_labels on each of the n markers in the list. 

Then, we can do our double nested for loop over that list of lists. I'm not sure how much of a speedup this will be, but I think it will make the code easier to read, so either way it's a plus. This will allow us to get rid of marker_1 and marker_2, have a single list of markers, and have the double for loop index into the same list with different indices

compute_close_cell_num_rand was basically an extension of this first function, with a third nested loop, so it has the same baggage. However, here we can't precompute close_cell_num, because that's what we're randomizing over

**Comment by ackagel** [comment]
Coolio. I already condensed the random version into:
```
close_num_rand = np.zeros((
    marker_num, marker_num, bootstrap_num), dtype='int')

dist_bin = np.zeros(dist_mat.shape)
dist_bin[dist_mat < dist_lim] = 1

for j, m1n in enumerate(marker1_num[:marker_num]):
    for k, m2n in enumerate(marker2_num[:marker_num]):
        close_num_rand[j, k, :] = np.sum(
            np.random.choice(dist_bin.flatten(), (m1n*m2n, bootstrap_num), True),
            axis=0
        )

return close_num_rand
```
and I can do something similar for the other one (doing the distance limiting before filtering by marker is probably faster)

**Comment by ngreenwald** [comment]
Wow, that's so much prettier. Pretty smart to have np handle the iterations dimension. Definitely worth taking a look at the non-random version too, but the reason I had this in the todo column and not the priority column was because our test suite currently only takes 3 minutes to run. Admittedly, these functions are a full 1.5 minutes of those 3 minutes...

![image](https://user-images.githubusercontent.com/13770365/90089277-c20d0780-dcd5-11ea-8286-8fd3a7ee21a1.png)

**Comment by ngreenwald** [comment]
Looks like this will close #130 as well!

**Comment by ackagel** [comment]
question about close_num calculation.  Right now, our close_num matrix will be symmetric.  In particular, if cell A is type 1, while cells B and C are type 2, and they're all close to each other, the resulting close_num matrix will currently be:
```
1 2
2 4
```
because the number of type 1 cells near type 2 cells is double counted since cell A is close to both cell B and C (B and C also double count each other).  Do we want this behavior, or do we want it so that the close num matrix is:
```
1 2
1 3
```
if we don't want self counting ( diagonal=(0,1) ), we can either filter out distances == 0 or subtract marker_num along the diagonal (the latter might be faster).

**Comment by ngreenwald** [comment]
Lets leave it as is for now. Leeat decided to count it this way, we can
discuss on Friday if it makes more sense to change it.
