### ISSUE TITLE
Create layout for documentation files

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#213]
The next step for our documentation is to start organizing the various files we're going to have on the RTD landing page. Currently, it pulls from the ReadMe and the docstrings. However, there are a number of additional files we're going to have for giving more in-depth explanation of different parts of the pipeline. Likely we won't just to paste them all in the readme. Instead, we'll have markdown versions of the files stored in the docs section of the github, and these can get rendered on readthedocs. 

Let's put together an example layout of what that would look like. There's a lot of flexibility here in terms of organization, so feel free to adapt any of these suggestions if you have ideas. 

The landing page: This should have the basic information about the repo, and link to the following:

Getting started for users: installation instructions using docker and bash script
getting started for developers: virtual-env instructions
Overview of the pipeline (#211)
Overview of different data types (#210), including xarrays (#209)
A link to our contributing guidelines (currently in docs)

What would be great is to create a placeholder file to represent each of these categories, so that we can see how it will look on RTD, how to link from one to another, etc. If you have other ideas for useful sections feel free to make a mockup of them as well. 

Then, once we're happy with the organization, we can actually go in and fill in the content for each of them.

**Comment by alex-l-kong** [comment]
So the basic idea I have is to have a separate _rtd folder in the docs directory. We can put all of our landing pages/virtual-env instructions/pipeline overview/etc. here, then include links to these in index.rst with the help of m2r2 and modify our toctree to format our table of contents more cleanly. Because _markdown is created remotely by ReadTheDocs, we can also link to these separately as well if need be.

**Comment by ngreenwald** [comment]
>  Because _markdown is created remotely by ReadTheDocs, we can also link to these separately as well if need be.

Could you explain this part? Everything else sounds good

**Comment by alex-l-kong** [comment]
> > Because _markdown is created remotely by ReadTheDocs, we can also link to these separately as well if need be.
> 
> Could you explain this part? Everything else sounds good

Yes, so originally, we were storing the documentation-specific .md files in the folder _markdown on GitHub. However, we're now telling ReadTheDocs to make that documentation on their end, eliminating the need for us to have our own _markdown directory. Instead, we now entrust the ReadTheDocs server to make the folder on their end, completely hidden from us.

Although we cannot see the folder on our end, we can still access the files in the folder in index.rst, because when ReadTheDocs parses it, it will have them for us.

**Comment by ngreenwald** [comment]
Got it. What will the format be for the files in the _rtd folder?

**Comment by alex-l-kong** [comment]
> Got it. What will the format be for the files in the _rtd folder?

All static .md files. Can't think of a reason to have additional subdirectories inside of _rtd for now unless we plan on having a lot of pages outside of our documentation.

Just to clarify, we're splitting this into 2 PRs: the first to define the structure (aka the _rtd folder, blank .md files inside, etc), and the second to actually fill the files with contents? Or am I thinking about this wrong?

**Comment by ngreenwald** [comment]
That's exactly right. The templates will allow us to see how they look on
RTD, as well as think about what categories we need. Then different people
can contribute to different portions of the next PR with the actual text
