### ISSUE TITLE
load_imgs_from_tree always sorts channels

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#262]
https://github.com/angelolab/ark-analysis/blob/eaf429e6efa25e29babf463c89d6a3de52410a3f/ark/utils/load_utils.py#L247

The current implementation now always sorts fovs and channels. These means it's not possible to specify the order of channels in the xarray by passing in a list, since they'll get resorted anyway. I think before we had it set up s.t. sorting only happened if None was provided. Is there a reason that we need to sort in all cases?

**Comment by alex-l-kong** [comment]
There is a call to sort the `channels` only if it is `None`, so it seems strange that we are resorting by `channels` again. The comment above the line you quoted says it is this way for a deterministic result; not sure what this means. I'll be doing some investigating and opening a PR to fix this if it turns out to be unnecessary.

**Comment by alex-l-kong** [comment]
I verified that not sorting by channel has no effect on the Segment_Image_Data notebook nor the other functions in ark. I'll open a PR to address this.

**Comment by ackagel** [comment]
Some context for that.  I added the 'deterministic' double sort, specifically so that `xr.equals` would work, since it's apparently order dependent (kinda lame imo).  Regardless, definitely not married to the idea, especially if it makes things more confusing for users.
