### ISSUE TITLE
Unable to get mask overlaid file due to channel names conflict

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#304]
**What are you trying to do?**
In the python script I try to segment a multi-channel tiff on
nucs = ['dsDNA']
mems = ['Na-K-ATPase','CD45','Keratin']

I am able to get the deep cell output file and the xarray file.

**What is the problem?**

When I try to create the masked overlay on the imaging data, ValueError: Invalid value for xr_channel_names. xr_channel_names length should be 2, as the number of channels in the input data.

**What have you tried so far?**
I tried to set the mems to one channel (Na-K-ATPase) and  I am able to get the mask overlaid file.  So it seems the problem occurs when I try to input multiple markers for membrane.
![Screen Shot 2020-10-27 at 6 41 37 PM](https://user-images.githubusercontent.com/58482675/97380358-114de780-1884-11eb-8175-577b67e5e837.png)

**Additional context**
Add any other context or screenshots here.

**Comment by HoxB8** [comment]
Update:  I don't have this problem when I use single-channel TIFs.

**Comment by ngreenwald** [comment]
Yup, here the problem is that you're loading the image that has been summed together (so one super membrane channel, one super nuclear channel) but the names we're passing it are the individual names for each channel, not the summed names. 

You can change the last line of the function call to be the following:
`
xr_channel_names = ['nuclear_channel', 'membrane_channel']
`
