### ISSUE TITLE
Speed up testing

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#336]
**Is your feature request related to a problem? Please describe.**
We have a couple tests that appear to be taking much longer than they should. 
![image](https://user-images.githubusercontent.com/13770365/99114494-bf0c0680-25a5-11eb-8068-e20df4753a0c.png)

In particular, `test_example_spatial_analysis`, `test_dimesionality_reduction`, and `test_draw_boxplot` all take a long time. 

**Describe the solution you'd like**
We should look into how to speed these up. Perhaps by passing in much smaller data for the test files (i.e. 100x100 instead of 1024x1024)

**Comment by alex-l-kong** [comment]
@ngreenwald so here are the current bottlenecks for the offending functions:

- `test_dimensionality_reduction`: we don't have a particularly large expression matrix (only 300 lines), the main time eater is that `UMAP` is inherently slow. We could try reducing this expression matrix by a factor of 3 or 5 to speed this up.
- `test_draw_boxplot`: so when I ran `pytest` on just `visualize_test.py`, there's no speed issues, but running `pytest` on the entire directory causes problems. Not sure why this is happening, will need further investigation.
- `test_example_spatial_analysis`: we can shave off some time by testing on a much smaller image, but I don't think we can reduce the bottleneck of sending the data to the DeepCell server. Not sure which one is the bigger bottleneck though.

**Comment by ngreenwald** [comment]
test_example_spatial_analysis doesn't send any data to deepcell. I'd prioritize the other stuff you're working on above this, but once you're blocked waiting for a review it will be worth investigating

**Comment by alex-l-kong** [comment]
@ngreenwald ha, sorry I was thinking of `Segment_Image_Data`. Didn't plan on taking this one on yet, just curious to see what was going on.

**Comment by alex-l-kong** [comment]
Update on this issue: we've fixed the time for `test_draw_boxplot`. We still need to look into `test_dimensionality_reduction` and `test_example_spatial_analysis` and testing on smaller images.

**Comment by ngreenwald** [comment]
Main thing is to see if there's any low-hanging fruit. Smaller example data, etc. Don't need to optimize underlying functions

**Comment by alex-l-kong** [comment]
@ngreenwald how high priority is it to speed up tests that depend on downloading the example dataset? These are inherently limiting for `test_download_example_data` and especially the full test of `test_segment_image_data`.

I'm a bit hesitant about removing `test_segment_image_data` since it's nice to have the dataset loading functionality tested in the notebook. However, it takes more than a minute to run. If it's worth reducing this workload, we can probably remove `test_segment_image_data`, since we already have granular tests for this notebook (`test_segment_image_data_mibitiff` and `test_segment_image_data_folder`). Might even be worth removing the mibitiff test because these are slowly becoming obsolete.

**Comment by ngreenwald** [comment]
For now the top priority is getting the example dataset working for all of the notebooks. Once it's stable and we've had users try it out, then we can see what optimization for tests is needed.
