### ISSUE TITLE
Benchmark SOM codebase

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#345]
Before we start optimizing a bunch of stuff, we should figure out what the current bottlenecks are, both in preprocessing, training, and running the trained SOM. 

To do this, I recommend using the `timeit` package. It allows you to create timestamps throughout your code. 

For example, 
```
from timeit import default_timer
start_time = default_timer()
# do task 1
time_1 = default_timer()
# do task 2
time_2 = default_timer()
print("task 1 took {} seconds".format(time_1 - start_time))
```

We should do this for all of the steps in the preprocessing, training, and running. I would suggest randomly generating 10 different 1024x1024x20 images to use for this.

**Comment by alex-l-kong** [comment]
Haven't benchmarked the SOM clustering step yet, but in `preprocess.py`, it's clear that the call to `ndimage.gaussian_filter` across 20 1024x1024 channels is the big time eater. Even if the optimizations provided by `apply_along_axis` are used, the Gaussian filtering still takes a little over a minute to complete for each image.

Removing the `fovs` loop with another `apply_along_axis` is one option for a minor speedup, but this does not eliminate the Gaussian filtering bottleneck. Python is embarrassingly bad with multithreading, but one interesting option using the `multiprocessing` library is presented here: https://stackoverflow.com/questions/45526700/easy-parallelization-of-numpy-apply-along-axis. The issue with this one is that it could be extremely memory intensive, but it's worth a shot.

**Comment by ngreenwald** [comment]
Got it, makes sense

**Comment by alex-l-kong** [comment]
@ngreenwald just benchmarked the SOM weight training, each step about as optimized as they can be, only taking on average 0.00001 seconds to complete. There are a total of 4 steps I timed, meaning on average on weight update takes just 0.00004 seconds.

This means the only bottleneck is the number of weight updates that need to happen. In the case of Candace's dataset, about 400,000,000 updates need to happen, meaning this process will take several hours to complete (on average 4.5).

The only way I can see this process being optimized is to take a small subset of the dataset. Since we already have a step for that in #287, I think we can close this issue.

**Comment by ngreenwald** [comment]
Before you close it, it would be useful to have a summary of how long each step takes right now. 

For example, the preprocessing, training a SOM for X steps, running the som on all of the data

**Comment by alex-l-kong** [comment]
@ngreenwald OK, so here's the complete rundown of the average times for Candace's dataset on a 2019 MacBook Pro 64 GB RAM machine:

- Preprocessing: 2 1/2 minutes
- 1 SOM weight update: insignificant (0.0004 seconds)
- 100000 SOM weight updates: 38 seconds
- 1 training pass through the dataset: 3.6 hours

Based on the calculations above, I expect the entire training to take around 36 hours, or about 2 hours and a day, and I'll have to restart the process completely because of a bug in saving the weights. Probably best to let Candace run the script herself and see if the results match up since she has the cloud resources to do so.

Do Stanford employees get a certain number of cloud credits for free?

**Comment by ngreenwald** [comment]
Agreed, there's no need to run it locally. The goal is that Candace runs it on the cloud, we see that the results are the same, and then we we can dramatically reduce number of steps in training. 
If it looks like more cloud troubleshooting is required, we can add you to the google cloud server we've been using and you can experiment there. 

How long does it take to run the trained SOM on the dataset?

**Comment by alex-l-kong** [comment]
@ngreenwald clustering using the SOM takes just over 18 minutes to run on the entire dataset.

**Comment by ngreenwald** [comment]
Right, and this dataset is fairly small. 

Do you have the R code for the next steps? Pixel metaclustering and stuff?

**Comment by alex-l-kong** [comment]
Yup, it's in one of the Drive links I shared with you.

**Comment by ngreenwald** [comment]
Okay cool. If you have some time to look over that code it would be useful to get familiar, but I think you should wait to start implementing it until we discuss with Candace tomorrow, since I think that part might still be in flux. I added two additional tasks (#362, #363) that can happen before that anyway.

**Comment by alex-l-kong** [comment]
Now that I have a more optimized clustering step (and verified that it produces the same outputs), here are the benchmarks (averages):

Total time (Candace's dataset): 12.6 minutes
Total time (`batch_size`=1000000): 18.5-19s
Sample - weight subtraction: 6.7s
Activation map calculation: 10-10.5s
Coordinate generation: 0.8s

As suspected, the activation map calculation is the biggest bottleneck here. It's a very complicated calculation and having to do it for 1000000 pixels at a time is quite expensive. However, the sample - weight subtraction is also expensive because the weights have to be subtracted from each sample individually.

I was disappointed that the speedup only ended up being just under 6 minutes, though a 1/3 speed improvement is pretty significant. I'm not sure if smarter batch sizing or extra multithreading/multiprocessing will help here, but regardless, I'll open a PR for the `batch_winner` function soon; we can discuss more there.

**Comment by ngreenwald** [comment]
Not sure I follow. Is it 12.6 minutes or 18.5 seconds?

**Comment by alex-l-kong** [comment]
@ngreenwald 12.6 minutes for the entire process (for Candace's dataset, just over 36,000,000 rows). 18.5-19s for one batch of 1,000,000 rows.

**Comment by ngreenwald** [comment]
Got it

**Comment by alex-l-kong** [comment]
@ngreenwald I think saving the data in feather format has provided a massive speedup here. Think we can close this issue?
