### ISSUE TITLE
Add additional batch-processing to segmentation notebook

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#415]
**Is your feature request related to a problem? Please describe.**
The current segmentation notebook has some steps which can be batch-processed, but some which cannot. This means that the total dataset size is still a limiting factor for processing a collection of images, which leads to memory errors (see #414)

**Describe the solution you'd like**
Rather than computing the amount of memory required, we should update the segmentation script to allow a batch size for all of the functions. 

Specifically, we'll need to do the following:
1. Modify ```generate_deepcell_input``` to take a path to the data_dir, rather than the full xarray. It will then read the data in one batch size at a time and process it
2. Remove the cell ("We can then load the segmented mask from deepcell via label-map TIFFs and save as an xarray") that loads all of the data and converts to an xarray. Instead, we can just load the first N images and use that for the subsequent script which plots example visualizations
3. Modify generate_cell_table to take a path to the segmentation directory, rather than an xarray with all of the labels.

**Comment by alex-l-kong** [comment]
@ngreenwald we run into a slight problem with removing "We can then load the segmented mask from deepcell..." because the visualization in the section "We can also then save the segmented mask..." requires the segmentation mask loaded in for overlay purposes.

The easiest fix would be to add the directory containing the segmentation labels (and possibly also the deepcell input directory so we can move the `data_xr_summed` load call) to `plot_utils.create_overlay`. Is this what you were envisioning or something else?

**Comment by ngreenwald** [comment]
Agreed, we can completely get rid of the "We can then load the segmented mask from deepcell..." section. Since we'll be batching everything, we don't need a single .xr file containing all the masks, we can read them from the deepcell output directory anytime we need to do something (i.e., creating the overlays and creating the processed data).
