### ISSUE TITLE
spatial analysis notebook uses legacy labels interface

### ISSUE THREAD

**Issue by ackagel** [angelolab/ark-analysis#443]
### **Description**
It seems like we no longer save labels as a `.xr` file in the segmentation notebook, but other notebooks (like spatial analysis) depend on `segmentation_labels.xr`.

### **To Reproduce**
 1. Run the segmentation notebook.
 2. Run the example spatial analysis notebook
 3. No `segmentation_labels.xr` exists so it errors out

### **Expected behavior**
Labels should be loaded in.

### **Fix**
Replace `.xr` loading with directory loading, or re-add `.xr` saving to segmentation notebook (could also be done behind the scenes).

**Comment by ngreenwald** [comment]
Yeah, we got rid of this because it's prohibitive for large cohorts. We'll need to update the other notebooks to have a batch-processing approach. 

Should be able to copy [this code](https://github.com/angelolab/ark-analysis/blob/823ecb5fd3f402363434711181a1917b0837cc80/ark/segmentation/marker_quantification.py#L499) as a work around until we update the notebooks
