### ISSUE TITLE
other bit depth tiff images

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#457]
Hello, I've been trying to segment other TIFs to see if it would work with DeepCell.  Is there any way for your script to take 16-bit or 8-bit TIFs?

**Comment by ngreenwald** [comment]
Yes, DeepCell/Mesmer should work without any problems for images of different depths. Some of the visualizations in the notebook, however, may fail. Did you get an error message?

**Comment by HoxB8** [comment]
Yes, when I tried to generate DeepCell input tifs with 16-bit TIFs, I get an error about dtypes (ValueError: Integer overflow from loading TIF image, try a larger type).    I then used ImageJ to convert the tifs to 32bit and everything ran without any issues.

![image](https://user-images.githubusercontent.com/58482675/131285587-525cd42b-0a42-4bb7-9401-1cc561f405de.png)

**Comment by ngreenwald** [comment]
Can you check and make sure the images you are trying to load in don't have any negative values? That's what the error message is indicating

**Comment by awedwards** [comment]
I'm also getting this same error for 32-bit images. The negative values error is likely due to overflow (which happens when a uint32 image is trying to be read as a uint16 image), rather than negative values in the raw data.

**Comment by ngreenwald** [comment]
Overflow makes sense for 32bit images being read in, since we default to int16, but it doesn't make sense for 8bit images.  @awedwards we have the option to specify the dtype in the helper function, `load_imgs_from_tree`. However, this isn't currently passed all the way up to the `generate_deepcell_input` function. Can you open a PR which adds this a kwarg? Should address both of these issues, you can then specify a larger dtype.

**Comment by awedwards** [comment]
Ah you're right, I misread what @HoxB8 was trying to do.

And sure I can open a PR

**Comment by ngreenwald** [comment]
Closed via #464
