### ISSUE TITLE
Bootstrapping in the spatial enrichment analysis

### ISSUE THREAD

**Issue by efrancis28** [angelolab/ark-analysis#485]
Request to modify the spatial enrichment analysis (calculate_cluster_spatial_enrichment, specifically compute_close_cell_num_random. For a for a pair of cell phenotypes (i, j), the bootstrap permutations should be done by only permuting the labels of j NOT both. This way the analysis becomes the enrichment of phenotype j around i. Otherwise this analysis is roughly symmetrical (aside from minor fluctuations from the bootstrapping).

**Comment by ackagel** [comment]
bootstrapping got corrected to this approach in PR #491 

side-caring onto the asymmetry train, right now, there can be multiple counts of the same cell if it's shared between two others i.e:
```
    B
A
    B
```
currently, A would have two B neighbors, _and_ B would have two A neighbors, despite each 'neighbor' being the same cell.  There's an argument that this won't greatly affect the enrichment scoring since this is also the case in the bootstraps, but we might want to look into whether one way or the other is better/different.
