### ISSUE TITLE
Cluster labels overlapping for cell GUI

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#536]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
The labels on the left side of the GUI are hard to see because of how they overlap each other

**Expected behavior**
The labels on the right side, which say the same thing, don't have this problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/13770365/166165136-6c90bbcf-27b7-4397-836e-cdd839342693.png)

**Comment by alex-l-kong** [comment]
I haven't tested it out yet, but I suspect this particular problem comes from this line in the `make_gui` call:

```
self.ddg = dendrogram(
    self.mcd.linkage_matrix,
    ax=self.ax_cd,
    orientation='left',
    labels=self.mcd.fixed_width_marker_names,
    leaf_font_size=8,
    )
```

As you can see, `leaf_font_size` is hard coded to 8. This probably worked well for fewer channels, however this may need to be shrunk for more channels. A more dynamic calculation may be in order.

Unfortunately, this isn't the only place where this problem pops up. Having worked with `metacluster_remap_gui` for a little bit now, it turns out Zak hardcoded a lot of a sizing and display parameters elsewhere too (they can't be modified in the `MetaClusterGui` constructor). For example:

```
width_ratios = [
            int(self.mcd.cluster_count / 7),
            self.mcd.cluster_count,
            self.mcd.metacluster_count,
            ]
height_ratios = [6, self.mcd.marker_count, 1, 1]
```

We don't need to address all of these, but I think we should leave open for consideration a gradual overhaul in this department.

**Comment by ngreenwald** [comment]
Got it. I think for now just changing the hardcoding for the font size on the left to match the hardcoding for the font size of the labels on the far right should do the trick, but I agree, lets see what other size issues pop up as more people use it

**Comment by alex-l-kong** [comment]
I took a deeper dive into this and it turns out it's easier to modify the `height_ratios` variable. Here's an example if I double `self.mcd.marker_count` to `self.mcd.marker_count * 2`:

<img width="1138" alt="Screen Shot 2022-05-18 at 2 33 04 PM" src="https://user-images.githubusercontent.com/31424707/169159419-e549c203-031d-4f74-981b-aa2368457fd8.png">

This is an extreme example but shows that we can either hard code a large value or programmatically determine a good multiplier based on the number of markers passed.

I'm going to link #550 here too because I suspect that issue can be resolved similarly by modifying the values in `width_ratios`.
