### ISSUE TITLE
Progress updates for compute intensive functions

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#566]
**Is your feature request related to a problem? Please describe.**
There are a number of functions in the clustering/spatial LDA processing that can take a long time. Some of them have progress bars, some of them print updates every 10 FOVs, and some of them have no output tracking. This makes it hard to know how long something will take

**Describe the solution you'd like**
We should standardize the way runtime info is displayed. There are two important pieces of information. 
1) How much progress has the function made
2) How much time has elapsed, and how much time is remaining

If the tqdm library can handle both of these for us, then that's great. I don't remember the exact issue with time estimate in the deepcell function, but if it's not accurate than it's not helpful to include. Instead, we can print elapsed time after set intervals.

**Comment by ngreenwald** [comment]
How many of these still need a progress bar?

**Comment by alex-l-kong** [comment]
@ngreenwald we now print out an update every 5 FOVs or so, for the cohort you tested on MIBIAN how long did it take to print out each update. If it's a significantly long time, perhaps we can consider adding a progress bar to each intermediate step too.

**Comment by ngreenwald** [comment]
So all of the pixel/cell clustering has either a progress bar or printed out FOV numbers? Is there anything in spatial LDA, KNN, etc that still needs this?

**Comment by alex-l-kong** [comment]
Spatial LDA will definitely need a second look at because of how long it takes, I don't remember if Calico updated their training function to display progress so I'll look into this over the weekend.

KNN I'm assuming refers to neighborhood analysis? It's been a hot while since I've run that notebook, I remember it not taking a very long time to run on the tests I did, but I'll look into this one as well just in case.

**Comment by ackagel** [comment]
Spatial enrichment doesn't have a progress bar currently; I can add one to the batching version this weekend, since those are the ones called by users anyways.

**Comment by alex-l-kong** [comment]
Per discussions with @ngreenwald and @cliu72, we'll need to add the following progress bars:

1. The EDA calculation in the spatial LDA preprocessing notebook
2. The KMeans clustering in neighborhood analysis. This point will require more discussion because silhouette score is prohibitively slow for massive cohorts. @cliu72 and I will be discussing a subsetting method.

**Comment by ngreenwald** [comment]
Talk to @ackagel, he did some work on the cluster evaluation for the spatial LDA preprocessing notebook. We should standardize across both notebooks if possible, and be consistent about what metrics we use

**Comment by alex-l-kong** [comment]
@cliu72 if the updated KMeans clustering in neighborhood analysis runs quickly with the new method, I can leave out the `tqdm` bar for that.

**Comment by alex-l-kong** [comment]
We will need to open a PR to address adding progress bar updates for `compute_cluster_metrics_inertia` and `compute_cluster_metrics_silhouette` in the neighborhood analysis notebook.
