### ISSUE TITLE
Spatial scripts require a `CLUSTER_ID` column, seems redundant with `CELL_TYPE`

### ISSUE THREAD

**Issue by cliu72** [angelolab/ark-analysis#713]
**Is your feature request related to a problem? Please describe.**
The spatial enrichment notebook and spatial LDA notebook require that the cell table has a `CLUSTER_ID` column, which should be integers representing unique cell types. The cell table already has a `CELL_TYPE` column, which corresponds to the cell phenotype names. These seem redundant to me. `CLUSTER_ID` and `CELL_TYPE` are referenced in `settings.py`. Right now it's confusing for users who are going from cell clustering to the spatial scripts, since there is no `CLUSTER_ID` column in the cell table.

**Describe the solution you'd like**
I think we need to either add functionality to the end of the cell clustering notebook to append this `CLUSTER_ID` column to the cell table (i.e. give each phenotype a unique integer). Or edit the spatial scripts to not use the `CLUSTER_ID` column and only use the `CELL_TYPE` column (since the information is redundant anyways). Option 1 is probably easier.

**Comment by ngreenwald** [comment]
What do you think about having spatial LDA and enrichment construct the numeric column when needed? One thing I suspect people will have is different cluster columns with different levels of granularity. If we just supply the column with names, and automatically generate the integers, then the user can pass whatever name column they want, rather than needing multiple different integer columns. 

The downside is that this would make the code a bit more complicated, and the user would need to specify the column for each notebook.

**Comment by cliu72** [comment]
Yeah I think having the spatial scripts construct the numeric column when needed is a good way to go. I think if the user wants to change the column they want, they would just need to change `settings.py`. Or is that file not supposed to be changed by the user?

**Comment by ngreenwald** [comment]
It's not supposed to be changed, but if we default the argument to whatever is in settings.py, and allow the user to overwrite it, I don't think it'll be an issue.
