### ISSUE TITLE
ark repo assumes square images

### ISSUE THREAD

**Issue by jonhsussman** [angelolab/ark-analysis#719]
After successfully running all the preprocessing and clustering steps, I am running into an error in Jupyter notebook on the step of `generate_and_save_pixel_cluster_masks`. Upon further inspection, I notice that the dimensions of the TIFF files (X * Y = 447,897,600 pixels) are different from the dimensions of the fov.feather file after the `create_pixel_matrix` step (len = 297,923,080). On a smaller image sample, there is still a difference but it is smaller (TIFF X * Y = 74,207,070, and len(feather) = 74,132,387). 

This discrepancy does not happen when we use the very small example data set provided (1,048,576 pixels), but seems to occur on our larger datasets. 

Below is the error message obtained in the Jupyter notebook. Although the pipeline removes empty pixels, there seems to be issues with the dimensions later on. It seems like as the images get larger, they are truncated and various problems begin to occur that I can't quite figure out. I know I wrote previously that I did some runs in conda, but this error occurred when strictly using Jupyter notebooks in the singularity container as is

Your help with this is very much appreciated! 

![image](https://user-images.githubusercontent.com/43019314/191603277-53a7cc13-75bf-4576-8e5b-237dff6a8e89.png)

**Comment by jonhsussman** [comment]
As a brief update on this, I think I found an error in the convert to 1D indexing function. The original formula looks incorrect because it produces values greater than the maximum index. I changed the 1 to a 2 in this image, but actually the x and ycoord should be switched instead. Changing this allows me to generate a plausible pixel map. I'll provide more details soon but wanted to share this initial solution. I'm not sure yet if the loss of pixels is also a problem or if this formula correction would solve the problem entirely


![image-14](https://user-images.githubusercontent.com/43019314/191648246-e1d16075-87c5-435b-badc-b18af6b69f34.png)

**Comment by alex-l-kong** [comment]
@jonhsussman thanks for pointing that out, to ensure complete correctness we'll make the change so `img_data.shape[2]` is used instead.

Because the vast majority of MIBI data applications tend to be 1024x1024 or 2048x2048, it doesn't usually make a difference if `img_data.shape[1]` or `img_data.shape[2]` is used. Would you happen to have images with different dimensions along the x- and y-axis.

**Comment by jonhsussman** [comment]
Great! 

I went back and confirmed that that formula error was causing the issue, and not the fact that it removes empty pixels, since I can see now that the metadata for the original pixel row and column is saved (so that wouldn't cause the index out of bounds error). I updated the title of the question to more accurately reflect this. 

That is correct, our images are generally rectangular with different dimensions along the x- and y-axis.

**Comment by ngreenwald** [comment]
Thanks for finding this @jonhsussman. We've made this assumption throughout the `ark` repo, since our MIBI images are always square. 

@alex-l-kong, can you take a look through the repo and see where else this might cause problems? Maybe just do a search for any `.shape` calls that we currently have, and see if any of them assume equal dimensions

**Comment by alex-l-kong** [comment]
@ngreenwald this looks like the only place where it's an issue (because of the way flattening each image explicitly changes the indexing method), so I can a very quick PR to address this.
