### ISSUE TITLE
`arrow` installation fails during Docker image build stage

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#744]
**Describe the bug**

The repository being referenced to download the `arrow` package in `R` cannot be accessed. This is preventing installation of the `arrow` package which is required for `feather` file handling in `R`.

**Expected behavior**

This package should download correctly.

**To Reproduce**

Run `docker build -t ark-analysis . > out.log 2>&1` locally. The relevant error message in `out.log` is:

![Screen Shot 2022-10-04 at 3 05 16 PM](https://user-images.githubusercontent.com/31424707/193938762-7a6bab60-d832-4247-be21-06ae49f922b5.png)

**Comment by ackagel** [comment]
spoiler alert, removing the `repos` optional arg from the `install.packages` function should resolve this.  

Passing in that repo arg lets it install arrow as a binary, instead of recompiling it locally.  I tested it on my end and it seemed like that worked, but as we know, dockerhub can have trouble building some images that we can build locally (for what seems like no reason).

The docker doesn't fail (i.e passes travis) because these errors are contained in R and don't pass up a non-zero exit code.  A script that runs all of the R-contained installs w/ validation logic would help with that, something like:
```R
install.packages('arrow', repos = '...')
...

if !library('arrow', logical.return=TRUE) {
    quit(status=1)
}
...
```
where this is ran in a loop for each package (idk the R syntax for that, but i'm sure you get the point).  The `quit(status=1)` will cause the docker build to fail, which will help prevent ark-incompatible R installations from making it to Dockerhub.

**Comment by alex-l-kong** [comment]
@ackagel yeah I think the easiest solution is to just use the default `arrow` installation, I when I checked R Package manager apparently doesn't support bullseye, only bionic, focal, and jammy. Think it's best not to use clashing distro packages here.
