### ISSUE TITLE
Investigate alternative to feather files

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#860]
**Is your feature request related to a problem? Please describe.**
The feather file format was used as an interoperable format between R and python. However, once we no longer have R code in the repo, this won't be necessary anymore. We occasionally ran into issues with feather files being corrupted, so an alternate format that works just as well would be nice
 
**Describe the solution you'd like**
Investigate the python-native data storage options, and benchmark them against feather files. How much compression is achieved? How long does it take to read, write, and compress? Are there file size limits? How reliable is it across platforms? etc etc

**Comment by alex-l-kong** [comment]
A few findings so far:

- `pyarrow.parquet` and `fastparquet` perform much worse than `feather` on all comparable levels of compression for writes. For a dataset of (10000000, 10), `pyarrow.parquet` performs about 2-3x worse, and `fastparquet` performs about 5x worse for write operations uncompressed (this difference gets further magnified for compressed files). Read operations are about comparable.
- HDF5 requires slightly more storage per FOV file, however it is a pretty neat solution that allows us to use a single file to store all our DataFrames (you can access dataframes using a key, which we can define as the FOVs). Writes tend to be faster for HDF5 compared to `feather` (about 1 sec difference), however reads tend to be faster for `feather` compared to HDF5 (also about 1 sec difference). It is extremely expensive to add compression to, however.
- The advantage of `feather` is efficiency with compression; it is very efficient compared to other libraries which could suffer up to 10-20x slowdown depending on the compression used. The downside is `feather` only supports 2 types of compression (`lz4` and `zstd`) and doesn't significantly compress the files (though this could add up to a huge saving with multiple files, especially `zstd`).
- `zarr`, unfortunately, doesn't have a great way to easily represent DataFrames. It's generally used as more of an array storage and operation library. This makes it a bit more challenging for us to use since we'll have to store the column names separately to properly map them back. It seems the community knows the problem exists and have brainstormed solutions, but nothing major has materialized yet.

Personally, I'm leaning either to sticking with `feather` or shifting to HDF5. The main benefit of sticking to `feather` is its read efficiency combined with fast write times. Our pipeline tends to be slightly more read-heavy than write-heavy due to the massive numbers of FOVs relied on for intermediate calculations. Additionally, if we need further compression, it will cost the least.

The strongest argument for shifting to HDF5 is the reduction of intermediate files needed. Its key-based store is very good in this regard, and I like the efficient write times. I think the time lost to reads (compared to `feather`) can be made up with its generally faster writes. Admittedly, though, I'm not sure how scalable it will be for hundreds or thousands of FOVs.

**Comment by ngreenwald** [comment]
Got it. Given that there's not an obvious, large advantage to switching, I think we should definitely keep things as is for now. The amount of work, losing backwards compatibility, etc doesn't seem worth it to me, especially since we have the files cordoned off in a separate folder, so it doesn't bother users. Thanks for looking into it!
