### ISSUE TITLE
2_pixie cluster pixel does not retrain SOM when new channel added

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/ark-analysis#887]
**Describe the bug**
When new channel is added, pixel preprocessing generates "New channels provided: overwriting whole cohort" and reprocesses the data. However going into - create the pixel-level SOM weights section does not regenerate the pixel SOM with new channel and instead get this msg - "Pixel SOM already trained". This results in an error when using pixel SOM weights to assign pixel cluster step. 

"1 value(s) provided for list pixel som weights columns and list pixel data columns are not found in both lists."

**Expected behavior**
Ability to add new channels and recluster
<img width="654" alt="Screenshot 2023-01-23 at 11 32 34 AM" src="https://user-images.githubusercontent.com/62519486/214108930-aede3c8e-6857-4735-81e4-7205293edd31.png">
<img width="1371" alt="Screenshot 2023-01-23 at 11 32 45 AM" src="https://user-images.githubusercontent.com/62519486/214108976-e9690833-4390-4291-bab9-7085d1f2bfaf.png">
<img width="1118" alt="Screenshot 2023-01-23 at 11 32 57 AM" src="https://user-images.githubusercontent.com/62519486/214109016-0b16200d-6373-4472-b22a-e763b23b5e13.png">

**Comment by ngreenwald** [comment]
@cliu72 what's your preference for the user logic here. Should we update all of the subsequent steps to check if the user has made changes? Or have them create a separate folder and start over? Or some other alternative?

**Comment by cliu72** [comment]
Hm I think it would be nice to have a check if the user has made changes (as opposed to having the user create a whole new folder and starting over). It seems like the preprocessing function is already checking for changes to the channels, but it's actually not checking if other things (i.e. blur sigma, subset proportion) are changed. I think those three (channels, blur sigma, subset proportion) are the three we need to check for - what do you think? I think especially when people are testing (like Hadeesha is right now), it'd be helpful for people to be able to make changes to these parameters and have them propagate.

**Comment by ngreenwald** [comment]
Sure, sounds good!

**Comment by alex-l-kong** [comment]
@cliu72 for verifying `channels` we can just read in the existing weights and verify that the `channels` columns match up. Since `blur_factor` and `subset_proportion` are parameters in `create_pixel_matrix` completely independent of the `PixelSOMCluster` class, for now one easy fix (albeit not clean) would be to save these preprocess variables (`blur_factor` and `subset_proportion`) in a JSON file and use that to verify the parameters didn't change.

More programmatically speaking, we should have all-encompassing classes for the entire Pixie pipeline (one for pixels, one for cells) which adds `create_pixel_matrix` as a method for pixel clustering and maintains `blur_factor` and `subset_proportion` attributes, as well as attributes of type `PixelSOMCluster` and `PixieConsensusCluster`. This will be a longer term project.

**Comment by alex-l-kong** [comment]
@cliu72 open to any other suggestions here too!

**Comment by cliu72** [comment]
I like your suggestion @alex-l-kong about verifying `channels` matches up with the existing weights. I also like eventually having all-encompassing classes for the entire Pixie pipeline - but I agree this is a longer term project and low priority.

After thinking about this some more, I think for now, we can just assume the user doesn't change `blur_factor` and `subset_proportion` (and just add that functionality of checking when we switch to the object-oriented version). I think the JSON option would work, but not worth the effort for something that isn't going to be used that often. Thanks Alex!
