### ISSUE TITLE
Can't run `cluster_cells` function more than once

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/ark-analysis#891]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

This is once again Candace and Hadeesha's account @cliu72 

**Describe the bug**
When you try to run the `cluster_cells` function more than once, there is an error. Reason seems to be because of these lines:
https://github.com/angelolab/ark-analysis/blob/7aadf27cb64e16fd0c293e1d1a36fb644c9a5425/ark/phenotyping/cell_cluster_utils.py#L543-554

Once you run `cluster_cells` one time, it adds the 'cell_som_cluster' column onto the `cluster_counts_size_norm` table, and those lines linked above checks to make sure that `cluster_counts_size_norm` and `weights` have the same column names. That is no longer true after you've ran `cluster_cells` once.

**Expected behavior**
Allow users to run `cluster_cells` more than once (this is probably not going to be common at all, but I still think it'll be better to support multiple runs). 

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 
<img width="1187" alt="Screenshot 2023-01-24 at 2 21 34 PM" src="https://user-images.githubusercontent.com/62519486/214400131-2ac72d2e-baa2-4d31-a8ed-0c5deb2ca76d.png">

**Comment by alex-l-kong** [comment]
@cliu72 (or @HPiyadasa lol don't which account's used) I think the easiest way to do this would be to specify an `overwrite` flag for both `train_pixel_som`/`train_cell_som` and `cluster_pixels`/`cluster_cells`. In this way we can allow the user to a force SOM training and assignment to happen again.

**Comment by alex-l-kong** [comment]
@cliu72 alternatively we could also set the flag in the notebook instead, although I think it would be better to just leave as a hidden param due to the rarity of this use case.

**Comment by cliu72** [comment]
Sure, I like this solution. Adding the `overwrite` flag in the function call sounds good to me.

**Comment by alex-l-kong** [comment]
@cliu72 after looking into this issue more, because `cluster_cells` and `cell_consensus_cluster` always run through the whole pipeline regardless of state, it's better not to add an `overwrite` flag for these two functions. Instead, we'll just check if the column `'cell_som_cluster'` already exists in `cluster_cells`.

I've added `overwrite` functionality to the entire Pixie pixel clustering process, as well as for cell SOM cluster training. I won't be adding an explicit variable in the notebooks to set overwriting, as this won't be common and can easily be found in the documentation.

**Comment by ngreenwald** [comment]
So if the overwrite flag defaults to false, and someone runs the pipeline a second time, does that mean they will still get this error? Is the behavior different for different steps in the process?

**Comment by alex-l-kong** [comment]
@ngreenwald not this specific error because `cluster_cells` won't actually use the `overwrite` flag, I've instead added custom logic to ensure `cell_som_cluster` gets dropped if it already exists.

The PR I've linked to this issue encompasses the broader problem of what happens if a user needs to rerun a second time, since it's currently impossible to "break out" of the check that skips any processing if certain files already exist. It's not always as simple as ensuring a column gets dropped.
