### ISSUE TITLE
Training Pixel SOM: Segmentation error (core dumped)

### ISSUE THREAD

**Issue by Pacomito** [angelolab/ark-analysis#962]
Hello,

Thank you very much for providing this very complete pipeline. 

**Describe the bug**
I successfully generated the pixel matrix with subset proportion of 5% on 28 fovs with dimensions varying from 3000x5000 to 6000x5000 pixels and 62 markers.
  
Then, running Train Pixel Som turns a `Segmentation error (core dumped)` after some time. However, running on a 128gb RAM  (Intel® Core™ i5-10500 CPU, Ubuntu 22.04.2 LTS) the memory is not fully used, suggesting it might not be a memory issue.
 

```
# create the pixel-level SOM weights
pixel_pysom = pixel_cluster_utils.train_pixel_som(  
    samples,
    channels.tolist(),
    args.output_dir,
    subset_dir=pixel_subset_dir,
    norm_vals_name=norm_vals_name,
    som_weights_name=pixel_som_weights_name,
    num_passes=1,
    seed=42
)
```

Running it with less samples, e.g. 10 or 15 fovs solved the issue, but I would really like it to run on the full dataset. Would you have an idea on how to overcome this issue ?

**Expected behavior**
Hopefully the training would finish on the 28 fovs with no error.

**To Reproduce**
In house data, not reproducible.
Ark analysis was installed with conda (ark-analysis 0.6.0.dev6)

**Comment by srivarra** [comment]
@Pacomito Could you provide the full error message? It can help us find the root cause of the segmentation error.

**Comment by Pacomito** [comment]
Unfortunately there are no additional errors.

I added some verbose in the `train_pixel_som` and `train_som` functions but this seems to happen in the `som` function that maps back to pyFlowSOM C code (cyFlowSOM.c):

Here are the logs:
```
There are no more FOVs to preprocess, skipping
Training SOM Pixel clustering
Initializing PixelSOMCluster
Reading norm_vals_path
Loading training data
Training SOM
Running som()...
Erreur de segmentation (core dumped)
```

**Comment by cliu72** [comment]
Hi @Pacomito! I just ran a test dataset using ~42 million total pixels (which should be similar to 5% of a 28 FOV, 6000 x 5000 pixel dataset) and 62 channels. I used a google cloud instance with 128 GB of RAM, and it was able to complete successfully. I've tried larger numbers of pixels before, and it has worked. Since I can't reproduce the error using a dataset of similar size, it's unfortunately a bit hard to debug for you. 

Even though the memory is not fully used, it could still be a memory issue. Are you using Docker? Docker limits the amount of RAM that it can use, so perhaps try increasing the Docker memory. Jupyter notebooks can also limit the amount of RAM that is used (https://stackoverflow.com/questions/57948003/how-to-increase-jupyter-notebook-memory-limit). Based on some googling, segmentation faults can be related to memory issues (https://stackoverflow.com/questions/1847789/segmentation-fault-on-large-array-sizes; https://stackoverflow.com/questions/18116297/error-segmentation-fault-core-dumped-arrays). Although since it's not a problem on our machine, I don't think it's a bug in the code.

Finally, just anecdotally, we have done some more subsampling tests with various datasets in the lab, and even for large datasets of a billion pixels, even just 10 million pixels was enough to capture the data variation (tried this on a few different datasets where we trained using the entire dataset and compared with training using 10 million pixels). Therefore, you can also try decreasing the subsampling. After the pipeline is done running, you can then compare the pixel clusters with the channel images and see if the pixel clusters make sense.

Hope this helps!

**Comment by Pacomito** [comment]
Hi @cliu72 , 

Thank you for this quick and comprehensive reply. Indeed it feels like it is a memory issue because working with less pixels works fine. 

I tried using a jupyter notebook but it also crashed at the same step. 

I will try with Docker, then subsample less pixels and let you know if it works ;)

**Comment by Pacomito** [comment]
Hello,

Using the Docker version + Jupyter Notebook worked for me and I had no more segmentation errors. I put the memory in Docker Desktop at 100Gb.

Thank you,
Pacome
