### ISSUE TITLE
plot_neighborhood_cluster_result has multiple colors per cell

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/ark-analysis#967]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
This function should assign each cell a unique color. However, upon closer inspection, it's clear that many cells are getting assigned multiple colors, but only at the borders. From a distance it's not clear, but a zoom in highlights the problem. 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/13770365/228930651-d30e790c-2730-49a6-95ec-9a7310e34543.png">
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/13770365/228930680-1297964c-9a89-42e1-aa0f-7bec64a12801.png">

This is after running the neighborhood analysis notebook, specifically this cell:
```
# load the masks in and plot them
for fov in subset_neighborhood_fovs:
    neighborhood_mask = load_utils.load_imgs_from_dir(
        data_dir=overlay_out_dir,
        files=[fov + "_neighborhood_mask.tiff"],
        trim_suffix="_neighborhood_mask",
        match_substring="_neighborhood_mask",
        xr_dim_name="neighborhood_mask",
        xr_channel_names=None,
    )

    plot_utils.plot_neighborhood_cluster_result(neighborhood_mask, [fov], k=k, save_dir=overlay_out_dir)
```

**Comment by camisowers** [comment]
It was an issue with plt.imshow() using a custom defined ListedColormap for int values instead of a colormap along a range. By default, imshow uses `interpolation='antialiased'` for boundary points. We can fix this by setting that arg to 'none'.

<img width="712" alt="Screenshot 2023-04-25 at 1 27 04 PM" src="https://user-images.githubusercontent.com/38049893/234395960-afad36f9-7674-4bae-81fc-81d29339b09e.png">
<img width="600" alt="Screenshot 2023-04-25 at 1 27 04 PM" src="https://user-images.githubusercontent.com/38049893/234396144-6ce29389-06f2-4b54-90ff-88f690daaa62.png">
