### ISSUE TITLE
Save `cluster_counts_size_norm` as it is being updated

### ISSUE THREAD

**Issue by HPiyadasa** [angelolab/ark-analysis#992]
This is candace on Hadeesha's account again. @cliu72 

**Is your feature request related to a problem? Please describe.**
After the Pixie refactoring, the code was changed such that `cluster_counts_size_norm` isn't saved to a feather file until the very end of the notebook. This is a problem when users with large datasets are not able to run the entire notebook in one sitting. Because `cluster_counts_size_norm` isn't saved, there is no way to map cells to cell clusters without going through the entire notebook. 

**Describe the solution you'd like**
Save `cluster_counts_size_norm` to the feather file after clustering and metaclustering are done (and before the end of the notebook).

**Comment by alex-l-kong** [comment]
@cliu72 we should add better fallback recovery for this to the cell clustering notebook as well. Here's one way we could do it:

1. If `cluster_counts_size_norm_path` already exists, load the file at the beginning instead of calling `create_c2pc_data` again. Same with `weighted_cell_channel_path`.
2. In `cluster_cells`, if `cell_pysom.cell_data` already has a `cell_som_cluster` column attached, return the data as is (and don't re-run the clustering step as we currently do). Add an explicit `feather.write_dataframe` command at the end of this cell.
3. Similar to step 2 but for `cell_consensus_cluster` and the `cell_meta_cluster` column. Add an explicit `feather.write_dataframe` command at the end of this cell.

Let me know if we're missing anything.
